EMAIL_PASS = "vgwk ebrp jiat wsmm"
EMAIL_USER  = "irapurubot@gmail.com"
EMAIL_CC = "mario.silva@irapuru.com.br, kevin.oliveira@irapuru.com.br"
EMAIL_DEST = "expedexpedicao.itapecerica@irapuru.com.br; operacional.recebimento@irapuru.com.br"